name: CI Pipeline

on:
  push:
    branches:
      - master
      - feature/*
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./coreplatform

    steps:
      # 1. Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Permisos para Gradle Wrapper
      - name: Grant Gradle permissions
        run: chmod +x gradlew

      # 4. Compilación, pruebas y reporte de cobertura (todo en uno)
      - name: Build and Test
        run: |
          ./gradlew assemble test jacocoTestReport --no-daemon
          echo "Build completado - Reporte de cobertura generado"

      # 5. Verificación de cobertura (>20%)
      - name: Verify Coverage
        run: |
          coverage=$(grep -oP '<counter type="INSTRUCTION".*' build/reports/jacoco/test/jacocoTestReport.xml | \
            sed -e 's/.*covered="\([^"]*\)".*missed="\([^"]*\)".*/\1 \2/' | \
            awk '{covered=$1; missed=$2; total=covered+missed; perc=covered*100/total; print perc}')
          echo "Cobertura actual: $coverage%"
          if (( $(echo "$coverage < 20" | bc -l) )); then
            echo "❌ Error: Cobertura insuficiente (<20%)"
            exit 1
          fi
